/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarcodeDemo: typeof import('./theme/components/BarcodeDemo.vue')['default']
    Home: typeof import('./theme/components/Home.vue')['default']
    HomeContributors: typeof import('./theme/components/HomeContributors.vue')['default']
    HomeSponsors: typeof import('./theme/components/HomeSponsors.vue')['default']
    HomeTeam: typeof import('./theme/components/HomeTeam.vue')['default']
    QRCodeDemo: typeof import('./theme/components/QRCodeDemo.vue')['default']
    TeamMember: typeof import('./theme/components/TeamMember.vue')['default']
  }
}
